channels:
  - conda-forge

dependencies:
  - python=3.10.12              # https://pyreadiness.org/3.9/
  - truststore=0.8.0
  - pip=23.2.1                  # https://pip.pypa.io/en/stable/news/
  - pip:
    - rpaframework==27.4.2      # https://rpaframework.org/releasenotes.html
    - rpaframework-recognition==5.2.3
    - robotframework-screencaplibrary==1.6.0
    - sauceclient==1.0.0
    - saucebindings==1.3.0