channels:
  - conda-forge

dependencies:
  - python=3.11.5              
  - truststore=0.8.0
  - pip=23.2.1                  
  - pip:
    - rpaframework==27.7.0      
    - rpaframework-recognition==5.2.3
    - robotframework-screencaplibrary==1.6.0
    - sauceclient==1.0.0
    - saucebindings==1.3.0